---
title: "R Notebook"
output: html_notebook
---

```{r warning=FALSE, message=FALSE}
library(dplyr)
# Import the relevant libraries
suppressWarnings(library(plyr))
suppressWarnings(library(tseries))
suppressWarnings(library(forecast))
suppressWarnings(library(lmtest))
#suppressWarnings(library(car))
#suppressWarnings(library(arfima))
#suppressWarnings(library(tsibble))
suppressWarnings(library(ggplot2))
suppressWarnings(library(gridExtra))
suppressWarnings(library(zoo))
```

```{r message=FALSE}
mf.tsdata <- read.csv("./machine_temperature_system_failure.csv")
mf.tsdata$timestamp_dt <- as.POSIXct(mf.tsdata$timestamp)
mf.tsdata$value_boxcox <- BoxCox(mf.tsdata$value, lambda = 3.5)
#head(mf.tsdata)

plot1 <- ggplot(mf.tsdata, aes(x = value_boxcox)) + geom_histogram()
plot2 <- ggplot(mf.tsdata, aes(sample = value_boxcox)) + stat_qq() + stat_qq_line()
grid.arrange(plot1, plot2, ncol=2)
```


```{r}
anomaly_points = c("2013-12-11 06:00:00",
                   "2013-12-16 17:25:00",
                   "2014-01-28 13:55:00",
                   "2014-02-08 14:30:00")

mf.tsdata$flag_anomaly <- ifelse(mf.tsdata$timestamp %in% anomaly_points, TRUE, FALSE)

mf.tsdata %>% filter(timestamp %in% anomaly_points)
```

### What is tghe distribution of the data? 

```{r}
ggplot() + 
  geom_line(mapping=aes(x=timestamp_dt, y=value_sqrt), data=mf.tsdata)
```


